[package]
name = "git-assistant"
version = "0.1.0"
authors = ["Simon KÃ¥gedal Reimer <skagedal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13.19"

[dev-dependencies]
temp_testdir = "0.2.3"
